const items = [
    {
        id: '001',
        item_image: '/Images/Items/1 (1).jpg',
        company_name: 'Carlton London',
        item_name: 'Rhodium-Plated CZ Floral Studs',
        original_price: 1045,
        current_price: 606,
        discount: 42,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.5,
            noOfReviews: 1400,
        },
    },
    {
        id: '002',
        item_image: '/Images/Items/2 (1).jpg',
        company_name: 'CUKOO',
        item_name: 'Women Padded Halter Neck Swimming Dress',
        original_price: 2599,
        current_price: 1507,
        discount: 42,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.3,
            noOfReviews: 24,
        },
    },
    {
        id: '003',
        item_image: '/Images/Items/3 (1).jpg',
        company_name: 'NUEVOSDAMAS',
        item_name: 'Women Red & White Printed A-Line Knee-Length Skirts',
        original_price: 1599,
        current_price: 495,
        discount: 69,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.1,
            noOfReviews: 249,
        },
    },
    {
        id: '004',
        item_image: '/Images/Items/4 (1).jpg',
        company_name: 'ADIDAS',
        item_name: 'Indian Cricket ODI Jersey',
        original_price: 999,
        current_price: 999,
        discount: 0,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 5.0,
            noOfReviews: 10,
        },
    },
    {
        id: '005',
        item_image: '/Images/Items/5 (1).jpg',
        company_name: 'Roadster',
        item_name: 'Pure Cotton T-shirt',
        original_price: 1399,
        current_price: 489,
        discount: 65,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.2,
            noOfReviews: 3500,
        },
    },
    {
        id: '006',
        item_image: '/Images/Items/6 (1).jpg',
        company_name: 'Nike',
        item_name: 'Men ReactX Running Shoes',
        original_price: 14995,
        current_price: 14995,
        discount: 0,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 0.0,
            noOfReviews: 0,
        },
    },
    {
        id: '007',
        item_image: '/Images/Items/7 (1).jpg',
        company_name: 'The Indian Garage Co',
        item_name: 'Men Slim Fit Regular Shorts',
        original_price: 1599,
        current_price: 639,
        discount: 60,
        rating: {
            stars: 4.2,
            noOfReviews: 388,
        },
    },
    {
        id: '008',
        item_image: '/Images/Items/8 (1).jpg',
        company_name: 'Nivea',
        item_name: 'Men Fresh Deodrant 150ml',
        original_price: 285,
        current_price: 142,
        discount: 50,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.2,
            noOfReviews: 5200,
        },
    },
];
